### ISSUE TITLE
Cannot Install through npm: SyntaxError

### ISSUE THREAD

**Issue by Agnishom** [purescript-contrib/node-purescript#59]
I cannot install purescript with npm. There appears to be some SyntaxError

```bash
agnishom@agnishomPC ~ $ npm --global install purescript
/home/agnishom/.nvm/versions/node/v6.11.1/bin/purs -> /home/agnishom/.nvm/versions/node/v6.11.1/lib/node_modules/purescript/purs.bin

> purescript@0.12.0 postinstall /home/agnishom/.nvm/versions/node/v6.11.1/lib/node_modules/purescript
> install-purescript --purs-ver=0.12.0 .

/home/agnishom/.nvm/versions/node/v6.11.1/lib/node_modules/purescript/node_modules/install-purescript/index.js:146
						...options
						^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/agnishom/.nvm/versions/node/v6.11.1/lib/node_modules/purescript/node_modules/install-purescript-cli/index.js:12:27)
npm ERR! Linux 4.13.0-26-generic
npm ERR! argv "/home/agnishom/.nvm/versions/node/v6.11.1/bin/node" "/home/agnishom/.nvm/versions/node/v6.11.1/bin/npm" "--global" "install" "purescript"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! purescript@0.12.0 postinstall: `install-purescript --purs-ver=0.12.0 .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the purescript@0.12.0 postinstall script 'install-purescript --purs-ver=0.12.0 .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the purescript package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     install-purescript --purs-ver=0.12.0 .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs purescript
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls purescript
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/agnishom/npm-debug.log
```

If it helps, this is my npm version:

```bash
agnishom@agnishomPC ~ $ npm --version
3.10.10
```

**Comment by shinnn** [comment]
Yes what @justinwoo said.

Details: https://github.com/purescript-contrib/node-purescript/issues/56#issuecomment-392345636
